CREATE TABLE Produto
(
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    Nome NVARCHAR(255) NOT NULL,
    Preco DECIMAL(18,2) NOT NULL,
    Quantidade INT NOT NULL,
    DataHoraCadastro DATETIME2 NOT NULL
);